name: Deploy to Firebase Hosting

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
          projectId: one-vow-l-p-nhlxnb   # ← あなたのプロジェクトIDにする
          channelId: live                 # 本番にデプロイ
          # entryPoint: ./                # firebase.jsonがルートに無い時だけ相対パスを指定
